server:
  port: 8081

spring:
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://39.108.222.138:3306/pauzooldb?useSSL=false&characterEncoding=utf8
    username: pauzool
    password: 62Nxc7pCQ3I=
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 解决mysql 8小时的问题
      validationQuery: SELECT "X"
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小Oracle，把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # 开启数据库密码解密
      # 开启Druid的监控统计功能


# mybatis配置
mybatis:
#  指定mapper包路径
  mapper-locations: classpath:mapping/*Mapper.xml
#  指定bean包名称
  type-aliases-package: com.cheap.entity
#  指定mybatis的配置文件路径
  config-locations: classpath:conf/mybatis-config.xml

# 日志配置
logging:
  pattern:
    console: "%d - %msg%n"
    level: debug

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# OkHttp3配置
okhttp3:
  enabled: true
  connect-timeout: 10
  follow-redirects: false
  follow-ssl-redirects: false
  ping-interval: 0
  read-timeout: 10
  retry-on-connection-failure: false
  write-timeout: 10